Correct BUG error message generation
On s390x when we compile we are getting

In file included from utils.c:30:
utils.c: In function '_sysfs_host_speed_get':
utils.c:189:39: error: '%s' directive output may be truncated writing up to 4095 bytes \
into a region of size between 4065 and 4075 [-Werror=format-truncation=]
  189 |             _lsm_err_msg_set(err_msg, "BUG: Unknown error %d(%s) from "
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
utils.h:53:41: note: in definition of macro '_lsm_err_msg_set'
   53 |     snprintf(err_msg, _LSM_ERR_MSG_LEN, format, ##__VA_ARGS__)
      |                                         ^~~~~~
utils.c:189:62: note: format string is defined here
  189 |             _lsm_err_msg_set(err_msg, "BUG: Unknown error %d(%s) from "
      |                                                              ^~
In file included from /usr/include/stdio.h:867,
                 from utils.h:23,
                 from utils.c:30:
/usr/include/bits/stdio2.h:67:10: note: '__builtin___snprintf_chk' output between \
42 and 4147 bytes into a destination of size 4096
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Change length so that we aren't trying to potentially stuff a 4K buffer
into a 4K buffer.

Signed-off-by: Tony Asleson <tasleson@redhat.com>