libses.c: Fix covscan SIZEOF_MISMATCH
Error: SIZEOF_MISMATCH (CWE-398): [#def1]
libstoragemgmt-1.3.0/c_binding/libses.c:449:
suspicious_pointer_arithmetic: Adding "28UL /* sizeof (struct
_ses_add_st_sas_phy) */ * i" to pointer "(struct _ses_add_st_sas_phy
*)&dp_sas->phy_list" of type "struct _ses_add_st_sas_phy *" is
suspicious because adding an integral value to this pointer
automatically scales that value by the size, 28 bytes, of the pointed-to
type, "struct _ses_add_st_sas_phy".  Most likely, the multiplication by
"sizeof (struct _ses_add_st_sas_phy)" in this expression is extraneous
and should be eliminated.

Signed-off-by: Gris Ge <fge@redhat.com>