lsmcli: Fix TypeError about bytes-like object on python3
Issue:
    Got error for cmdtest on python3:
        Traceback (most recent call last):
          File "/tmp/6640/bin//cmdtest.py", line 1040, in <module>
            run_all_tests(c, system[ID])
          File "/tmp/6640/bin//cmdtest.py", line 997, in run_all_tests
            test_local_disk_led()
          File "/tmp/6640/bin//cmdtest.py", line 961, in test_local_disk_led
            disk_path], expected_rcs=expected_rcs)
          File "/tmp/6640/bin//cmdtest.py", line 932, in verify_no_daemon_needed
            if 'DAEMON_NOT_RUNNING' in err:
        TypeError: a bytes-like object is required, not 'str'

Root cause:
    Python3 are use bytes mode for subprocess.PIPE.

Fix:
    Decode bytes into utf-8 string.

Signed-off-by: Gris Ge <fge@redhat.com>