libsg.c: Fix coverity warning
libstoragemgmt-1.3.2/c_binding/libsg.c:674: error[sprintfOverlappingData]:
Undefined behavior: Variable 'err_msg' is used as parameter and destination in s[n]printf().

Signed-off-by: Tony Asleson <tasleson@redhat.com>