Fix 'make check' on RHEL 6(python 2.6)
Problem:
    Got below error when run 'make check' on RHEL/Centos 6.
    ERROR: test_invalid_uri (__main__.TestPlugin)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/10441/bin//plugin_test.py", line 1582, in test_invalid_uri
        with self.assertRaises(lsm.LsmError):
    TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
    ----------------------------------------------------------------------

Root cause:
    'with self.assertRaises(lsm.LsmError)' is only supported by
    python 2.7+ while RHEL6 only ships python 2.6

Fix:
    Change to:

        self.assertRaises(lsm.LsmError, lsm.Client,
                          "ontap//root@na-sim", "some_password")

Signed-off-by: Gris Ge <fge@redhat.com>